[package]
name = "runtime"
version = "0.2.4"
authors = ["Interlay <contact@interlay.io>"]
edition = "2018"

[dependencies]
parity-scale-codec = "1.3.1"
frame-support = "2.0.0"
frame-system = "2.0.0"
async-trait = "0.1.40"
sp-runtime = "2.0.0"
sp-arithmetic = "2.0.0"
sp-core = "2.0.0"
thiserror = "1.0"
serde_json = "1.0.57"
serde = "1.0.116"
tokio = { version = "0.2.22", features = ["full"] }
jsonrpsee = "0.1.0"
futures = "0.3.5"
substrate-subxt-proc-macro = { git = "https://github.com/paritytech/substrate-subxt", rev = "27c377a" }
substrate-subxt = { git = "https://github.com/paritytech/substrate-subxt", rev = "27c377a" }
clap = "3.0.0-beta.2"
sp-keyring = "2.0.0"

[dependencies.btc-parachain-runtime]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.4.0"
package = "btc-parachain-runtime"

[dependencies.module-bitcoin]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.4.0"
package = "bitcoin"

[dependencies.module-refund]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.3.1"
package = "refund"

[dependencies.module-btc-relay]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.4.0"
package = "btc-relay"

[dependencies.module-security]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.3.0"
package = "security"

[dependencies.module-staked-relayers]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.4.0"
package = "staked-relayers"

[dependencies.module-vault-registry]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.4.0"
package = "vault-registry"

[dependencies.module-exchange-rate-oracle-rpc-runtime-api]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.3.0"
package = "module-exchange-rate-oracle-rpc-runtime-api"

[dependencies.module-issue]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.4.0"
package = "issue"

[dependencies.module-redeem]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.4.0"
package = "redeem"

[dependencies.module-replace]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.4.0"
package = "replace"

[dependencies.module-exchange-rate-oracle]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.3.0"
package = "exchange-rate-oracle"

[dev-dependencies]
substrate-subxt-client = "0.4.0"
tempdir = "0.3.7"
sp-keyring = "2.0.0"

[dev-dependencies.btc-parachain]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.4.0"
